name: Daily News 9am CST

on:
  schedule:
    - cron: "0 1 * * *"   # 每天 01:00 UTC = 北京时间 09:00
  workflow_dispatch:      # 允许网页手动运行

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Run digest + email
        env:
          OPENAI_COMPATIBLE_BASE_URL: ${{ secrets.OPENAI_COMPATIBLE_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: ${{ secrets.MODEL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: |
          python news_agent_pro_v2.py --html --wechat --email

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ github.run_id }}
          path: |
            digests/*.md
            digests/*.html
          if-no-files-found: warn
