name: Daily News 9am CST

on:
  schedule:
    - cron: "0 1 * * *"   # 每天 01:00 UTC = 北京时间 09:00
  workflow_dispatch:      # 允许网页手动运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install feedparser requests beautifulsoup4 PyYAML tenacity python-dotenv markdown

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo "---- recursive ----"
          ls -R

      - name: Ensure required files exist (bootstrap)
        run: |
          # 1) 脚本必须在仓库根目录
          test -f news_agent_pro_v2.py || { echo "::error file=news_agent_pro_v2.py::script not found at repo root"; exit 1; }

          # 2) 最小可用 config/prompt/template（若你仓库已有就不会覆盖）
          mkdir -p prompts templates digests
          if [ ! -f config.yaml ]; then
            cat > config.yaml <<'YAML'
feeds:
  - name: Reuters Top
    url: https://feeds.reuters.com/reuters/topNews
  - name: Electrek EV
    url: https://electrek.co/guides/ev/feed/
  - name: TechCrunch
    url: https://techcrunch.com/feed/
  - name: 36kr
    url: https://36kr.com/feed
topics:
  - name: EV 与 LCV
    keywords: ["EV","electric","电动车","汽车","Tesla","丰田","大众","起亚","现代","LCV","卡车","货车"]
  - name: AI 与数字化
    keywords: ["AI","人工智能","模型","LLM","OpenAI","Nvidia","Google","Meta","微软","苹果","生成式"]
  - name: 欧洲政策与监管
    keywords: ["EU","Europe","欧洲","欧盟","政策","监管","ECB","Tariff","关税","digital euro"]
  - name: 投融资与市场
    keywords: ["融资","并购","IPO","投资","VC","并购","Funding","Invest","Series"]
YAML
          fi

          if [ ! -f prompts/bilingual_system.txt ]; then
            cat > prompts/bilingual_system.txt <<'TXT'
You are a concise bilingual news summarizer. Given JSON grouped by topic, produce a Chinese digest and a short English TL;DR.
TXT
          fi

          if [ ! -f templates/base.html ]; then
            cat > templates/base.html <<'HTML'
<!doctype html><html lang="zh"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body{{margin:0;background:#fff;color:#1f2937;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Noto Sans","PingFang SC","Hiragino Sans GB","Microsoft YaHei","Helvetica Neue",Arial,sans-serif;line-height:1.6}}
  .wrap{{max-width:820px;margin:48px auto;padding:0 20px}}
  h1{{margin:0 0 6px;font-size:28px}} .sub{{color:#6b7280;font-size:14px}}
  article{{background:#fff;padding:24px;border-radius:14px;box-shadow:0 2px 8px rgba(0,0,0,.06);margin-top:18px}}
  a{{color:#2563eb;text-decoration:none}} a:hover{{text-decoration:underline}}
  pre{{background:#f3f4f6;padding:12px;border-radius:8px;overflow:auto}}
  .foot{{color:#6b7280;font-size:13px;margin-top:20px}}
</style></head>
<body><div class="wrap">
<header><h1>{title}</h1><div class="sub">{subtitle}</div></header>
<article>{content}</article>
<div class="foot">由 Daily News Agent 生成 · {date}</div>
</div></body></html>
HTML
          fi

      - name: Run digest + email
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO:  ${{ secrets.MAIL_TO }}
          OPENAI_COMPATIBLE_BASE_URL: ${{ secrets.OPENAI_COMPATIBLE_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: ${{ secrets.MODEL }}
        run: |
          python news_agent_pro_v2.py --html --wechat --email

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ github.run_id }}
          path: |
            digests/*.md
            digests/*.html
          if-no-files-found: warn
